### ISSUE TITLE
Why Drupal?

### ISSUE THREAD

**Issue by Firesphere** [ddev/ddev-drupal9-solr#18]
Aside from the documentation on how specifically use it with Drupal's solr_search_api module, I don't see any reason why this container would be Drupal-specific?

**Comment by rfay** [comment]
The service is certainly not drupal-specific. The story of this add-on is that folks in the Drupal world have always had a horrible time getting Solr configured because of all the various things you have to do. This add-on is the descendant of a recipe on github.com/ddev/ddev-contrib, which is a descendant of an old blog post. 

If you're interested in adding info on how to use it with another CMS or framework, a PR is welcome! And if it can be more general, it could probably have a name change. And of course... new add-ons are easy.

**Comment by Firesphere** [comment]
I found that it indeed works just fine with other frameworks, and have added some documentation.

**Comment by rfay** [comment]
@Firesphere where did you add the documentation? Would you like to do a PR here?

**Comment by Firesphere** [comment]
I _thought_ I made a PR... But I think it may not be opened/finished yet, I'll have to check my other laptop

**Comment by Firesphere** [comment]
Yep, I hadn't hit the final "create PR" button.
