### ISSUE TITLE
Drop drupal version (9) from project name

### ISSUE THREAD

**Issue by bserem** [ddev/ddev-drupal9-solr#36]
I see people are avoiding the use of this addon because it says `drupal9` on the project name. It only happens with people newer to DDEV.

With drupal9 being EOL, I would advise to rename the project and completely remove the core version from that and the description.

**Comment by rfay** [comment]
The actual recommended add-on, maintained by the maintainer of search_api_solr is the ddev-solr add-on. Interested in your thoughts on right path forward. I'm ok with rename, demotion...

**Comment by bserem** [comment]
Then maybe we should decommission this one, in favor of ddev-solr.

The thing is that `ddev get --list` displays an addon that says "drupal9" in it's name. That's confusing to people. I've been using it in D9 projects and continue to use it now. I had discussions with people asking me where is the D10 version.
And to be honest, I never thought of using ddev-solr, since there was a "more" drupal version.

**Comment by rfay** [comment]
The problem is that so many people use this one. And, frankly, it's a bit simpler. 

Would you be willing to take on the maintenance of this add-on?

I'd be fine with any of these directions. I think this one should at least
* Rename
* Update the README  (and explain the difference, etc)

**Comment by bserem** [comment]
I admit that I've been using this one too since it appeared. I don't mind trying to maintain this one (time is a bit limited right now), but shouldn't we have just one?

If ddev-solr is the way to go, then maybe we should deprecate this?

Decisions... decisions... decisions..

**Comment by rfay** [comment]
This one is definitely simpler and smaller, but ddev-solr is "the recommended technique". As a non-solr-expert I have trouble following such a complex subject. 

Let's at least deprecate as far as referring to the other one clearly in the README, and let's change the title. But maybe `ddev-olddrupal-solr` ? `ddev drupal-oldsolr` ?

I gave you maintainer privs on this. Let me know what I can do to help.

**Comment by bserem** [comment]
In that case, I would suggest `ddev-drupal-simple-solr` or `ddev-drupal-solr`.

I've been reading the other projects README. I understand there is place for a simpler approach just for Drupal (since Solr is so popular in Drupal).
I'll try to identify all the differences and document them here. _If time allows I'll even try_ the other project to get a better picture of what it offers and how harder it is.

Thanks for the privileges, it's an honour.
If we can decide to ditch `9` from `drupal9` then I guess it's a good first step. So I would need your help with that :)

**Comment by rfay** [comment]
Absolutely let's get rid of the '9'. Just let me know what the new name should be and I'll do it. `ddev-drupal-simple-solr` would be fine with me. I do want to honor @mkalkbrenner and his maintenance and effort that's gone into ddev-solr, and of course as the maintainer of Drupal's search_api_solr he should have lots of sway here. Maybe `ddev-drupal-simpler-solr` ?

I think redirects should work fine, but I'd rather not have multiple redirects, so we'll just figure out one time what the change should be. `ddev-drupal-simplest-solr` ?

**Comment by bserem** [comment]
I'll wait for @mkalkbrenner too. I won't be surprised if he suggests that `ddev-solr` is simpler, which seems to be the case since it has the possibility to auto-update the config judging by the README! So lets wait for him.

`drupal-simple` is simple, `simplest` might have people expecting they don't have anything to do, they'll still have to set the core etc.

The files in the addon are already ok from what I can tell. So, people using `ddev get ddev/ddev-drupal9-solr` would simply continue with `ddev get ddev/ddev-drupal-solr` (or what we name it).

In reality, it's just that `9` that confuses people.

**Comment by rfay** [comment]
No, let's not wait for him to chime in, he's busy and doesn't care for this one anyway :) `ddev-simple-solr` is OK with me if you like it.

**Comment by rfay** [comment]
> In reality, it's just that 9 that confuses people.

The thing is, the other one is the one preferred for search_api_solr, and thus for Drupal. So naming this `ddev-drupal-solr` seems to defeat so many things. 

How about renaming to `ddev-drupal-solr` and adding output in the install that mentions ddev-solr, and of course making strong recommendation in the README?

**Comment by mkalkbrenner** [comment]
Thanks for asking me.
"my" version also covers solarium in the README. I think Solarium is used in 99% of the use-cases. But maybe not directly but hidden because of integrations like the TYPO3 or Wordpress plugins or the bundles for symfony or laravel. The truth is that any of these could directly use Solr in Cloud mode without any problem as the way of the connection is backward compatible. If they connect the classic way, they simply can't use the advanced cloud features.
I know many of the Solr hosting service providers. Especially those who are not focused on Drupal use Solr Cloud as backend.
So I think there should be only one Solr integration for Ddev, based on Solr Cloud. BTW, the current one starts only one node as this is sufficient for local development in most cases. So it doesn't require much more resources compared to a Solr instance running in classic mode.
The only real differences between cloud and classic are the way a config-set gets deployed and how a new "core" gets created. And that's the only real issue because the cloud mode is not covered in the READMEs of most frameworks.
So if we could offer a generic PHP script in the Solarium project and a ddev command to call it to deploy a config-set and to create a core leveraging the cloud APIs in the background, we'll have the simplest Solr integration for ddev that is possible. In other words, the task is to have a pure PHP equivalent to the existing Drupal Drush commands for deployment and to only offer Solr Cloud mode.

**Comment by rfay** [comment]
@mkalkbrenner would appreciate if you could also comment on 
* https://github.com/ddev/ddev/issues/5860 

I'm sure you have dealt with many people's resistance, but it does seem to continue. I have hoped for your `ddev-solr` to work for everybody as well.

**Comment by rfay** [comment]
Let's move forward on this @bserem , thanks.

**Comment by bserem** [comment]
I made a PR and changed the description of the project to mention ddev-solr, so that it gets visible into the `ddev get --list` table.

The next step would be to rename the project @rfay
In the future we could consider deprecating this entirely, but for now I feel it's ok to point people to the better alternative and let them decide.

**Comment by rfay** [comment]
Project is renamed.

**Comment by rfay** [comment]
> In the future we could consider deprecating this entirely, but for now I feel it's ok to point people to the better alternative and let them decide.

Consider stronger language when mentioning ddev-solr then, saying that "`ddev-drupal-solr` may be deprecated in the future" or something.

**Comment by rfay** [comment]
This was completed. I think there's probably still some cleanup to be done @bserem , thanks!
