### ISSUE TITLE
README needs to be updated, since search_api_solr_defaults module no longer exists

### ISSUE THREAD

**Issue by joestewart** [ddev/ddev-drupal9-solr#7]
It appears the search_api_solr_defaults module was removed from search_api_solr 4.x
https://www.drupal.org/project/search_api_solr/issues/3295726

The step in the README can't be used.

"Enable the Search API Solr Search Defaults module: ddev drush en -y search_api_solr_defaults. (If it can't be enabled due to the "article" content type not existing, you can just create a search_api_solr server manually.)"

**Comment by rfay** [comment]
@joestewart could you do a PR to update? @mkalkbrenner can you confirm and/or offer other guidance?

**Comment by mkalkbrenner** [comment]
Yes, search_api_solr_defaults has been removed from the search_api_solr module.
Since it was just for demonstration purposes and its tests failed with newer Drupal 9.x cores, we decided to remove it.

@joestewart maybe you can try https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/solr

**Comment by rfay** [comment]
@mkalkbrenner that same set of steps is already baked into this add-on. The thing that's wrong is the README, because of the change. And IIRC, the same problem is in the ddev-contrib README.

**Comment by mkalkbrenner** [comment]
@rfay Sorry, but I don't understand what you mean.

> that same set of steps is already baked into this add-on.

Baked into which add-on?

> And IIRC, the same problem is in the ddev-contrib README.

There's nothing about **search_api_solr_defaults**

**Comment by tyler36** [comment]
@mkalkbrenner 

> that same set of steps is already baked into this add-on.

This addon (drud/ddev-drupal9-solr) copies the `docker-compose` & `solr` files into the appropriate `.ddev` directory.  

View [`install.yaml`](https://github.com/drud/ddev-drupal9-solr/blob/main/install.yaml) to see exactly what it is doing.

**Comment by tyler36** [comment]
@rfay 

A quick [search of ddev-contrib](https://github.com/drud/ddev-contrib/search?q=search_api_solr_defaults) shows zero hits of "search_api_solr_defaults".

**Comment by rfay** [comment]
You're certainly right, sorry. There has been a pile of change in the Drupal Solr world in the last year or so and @mkalkbrenner did a completely new setup in recent times, to track the work he's done with search_api_solr. I've been hoping to get his new solr cloud work into a new add-on but we haven't gotten it to pass muster yet in ddev-contrib, see https://github.com/drud/ddev-contrib/pull/195

What I'd like is to use the new approach here. 

I can't even find a reference to search_api_solr_defaults in https://ddev.com/ddev-local/apache-solr-with-drupal-8-and-search-api-solr/, which I thought might have been the source. And it's certainly not mentioned in the current https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/solr

There are two things here:

1. This is the pre-solr-cloud recipe which is most often used in the Drupal community still. But it needs the defaults module removed and it needs the step-by-step configuration added in so that people have it.
2. The solr cloud approach that @mkalkbrenner prefers is the one in https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/solr and https://github.com/drud/ddev-contrib/pull/195 - It's a very different approach, and will probably need a new add-on. I had been hoping to get https://github.com/drud/ddev-contrib/pull/195 sorted out and do that quite some time ago, but we haven't made progress there.

**Comment by rfay** [comment]
All that's required here @joestewart is to fix up the README to tell people how to set the defaults that are required (and NOT enable that module). Would you be willing to do a PR to the README doing that? It's so much better to have people using the project do things with it. Especially if you are a regular user of solr.

**Comment by cspitzlay** [comment]
See https://github.com/drud/ddev-drupal9-solr/pull/8

**Comment by rfay** [comment]
If everybody could test the new instructions in #8 using a fresh Drupal 9 project that would be awesome!
